# Generated by Django 6.0.4 on 2026-04-08 19:05

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('NO_VIOLATION', 'No Violation'), ('CONTENT_REMOVED', 'Content Removed'), ('WARNING', 'Warning'), ('TEMP_BAN', 'Temporary Ban'), ('PERM_BAN', 'Permanent Ban')], max_length=32)),
                ('note', models.TextField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationActionHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('action', models.CharField(choices=[('NO_VIOLATION', 'No Violation'), ('CONTENT_REMOVED', 'Content Removed'), ('WARNING', 'Warning'), ('TEMP_BAN', 'Temporary Ban'), ('PERM_BAN', 'Permanent Ban')], max_length=32)),
                ('note', models.TextField(blank=True, default='', max_length=512)),
                ('moderator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_note_moderator_events', to='moderation.moderationaction')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=32)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_cases', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderation.moderationcase'),
        ),
        migrations.CreateModel(
            name='ModerationCaseHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=32)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_priority_events', to='moderation.moderationcase')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='moderation.moderationcase')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_content_types', models.ManyToManyField(blank=True, help_text='Content types this reason applies to. Leave empty to allow for all targets.', related_name='report_reasons', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='moderation.moderationcase')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='description_reason_case_events', to='moderation.report')),
                ('reason', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='moderation.reportreason')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='moderation.reportreason'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='moderation__status_c5a537_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['content_type', 'object_id'], name='moderation__content_7c5992_idx'),
        ),
        migrations.AddConstraint(
            model_name='moderationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'UNDER_REVIEW'))), fields=('content_type', 'object_id'), name='unique_active_case_per_target'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moderationcase',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "moderation_moderationcasehistory" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "status") VALUES (_pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority", NEW."status"); RETURN NULL;', hash='85720a617a7e91b1760abfd6e89a0a93a441c381', operation='INSERT', pgid='pgtrigger_insert_insert_fa4db', table='moderation_moderationcase', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moderationcase',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."priority" IS DISTINCT FROM (NEW."priority") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "moderation_moderationcasehistory" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "status") VALUES (_pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority", NEW."status"); RETURN NULL;', hash='8af7c6b869be57b6448f318309ac4ad8bede4742', operation='UPDATE', pgid='pgtrigger_update_update_e582f', table='moderation_moderationcase', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moderationaction',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "moderation_moderationactionhistory" ("action", "moderator_id", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."action", NEW."moderator_id", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='becb50058ec5dc398e63cecef9a33f7685565baa', operation='INSERT', pgid='pgtrigger_insert_insert_ec7c5', table='moderation_moderationaction', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='moderationaction',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."action" IS DISTINCT FROM (NEW."action") OR OLD."moderator_id" IS DISTINCT FROM (NEW."moderator_id") OR OLD."note" IS DISTINCT FROM (NEW."note"))', func='INSERT INTO "moderation_moderationactionhistory" ("action", "moderator_id", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."action", NEW."moderator_id", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='e17137ee18ebbb71d95f6611c1cbbc98629ce41d', operation='UPDATE', pgid='pgtrigger_update_update_2aec7', table='moderation_moderationaction', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['case', 'created_at'], name='moderation__case_id_b7fdb3_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', 'created_at'], name='moderation__reporte_d53858_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='moderation__content_408935_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'case'), name='unique_report_per_reporter_per_case'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='report',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "moderation_reporthistory" ("case_id", "description", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_id") VALUES (NEW."case_id", NEW."description", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason_id"); RETURN NULL;', hash='d440c82cf445efdabf873de507750458eb6910a1', operation='INSERT', pgid='pgtrigger_insert_insert_62e14', table='moderation_report', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='report',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."case_id" IS DISTINCT FROM (NEW."case_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."reason_id" IS DISTINCT FROM (NEW."reason_id"))', func='INSERT INTO "moderation_reporthistory" ("case_id", "description", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_id") VALUES (NEW."case_id", NEW."description", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason_id"); RETURN NULL;', hash='4fc841bbaf6cbe6a26dcfebb5f51c2ae8a0297f0', operation='UPDATE', pgid='pgtrigger_update_update_68fde', table='moderation_report', when='AFTER')),
        ),
    ]
