# Generated by Django 6.0.3 on 2026-03-05 18:40

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('body', models.TextField(max_length=2048)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=32)),
                ('moderator_note', models.TextField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_content_types', models.ManyToManyField(blank=True, help_text='Content types this reason applies to. Leave empty to allow for all targets.', related_name='report_reasons', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('body', models.TextField(max_length=2048)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=32)),
                ('moderator_note', models.TextField(blank=True, default='', max_length=512)),
                ('moderator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='body_reason_status_moderator_note_moderator_events', to='moderation.report')),
                ('reason', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='moderation.reportreason')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='moderation.reportreason'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='moderation__status_2a84ce_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'created_at'], name='moderation__user_id_1e46cf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='moderation__content_c7ab8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'UNDER_REVIEW'))), fields=('user', 'content_type', 'object_id'), name='unique_active_report_per_user_target', violation_error_message='You already have an active report targeting this content.'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='report',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "moderation_reporthistory" ("body", "moderator_id", "moderator_note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_id", "status") VALUES (NEW."body", NEW."moderator_id", NEW."moderator_note", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason_id", NEW."status"); RETURN NULL;', hash='de694067b6ef63812e5c4bf15d8ca933e8617009', operation='INSERT', pgid='pgtrigger_insert_insert_62e14', table='moderation_report', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='report',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."moderator_id" IS DISTINCT FROM (NEW."moderator_id") OR OLD."moderator_note" IS DISTINCT FROM (NEW."moderator_note") OR OLD."reason_id" IS DISTINCT FROM (NEW."reason_id") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "moderation_reporthistory" ("body", "moderator_id", "moderator_note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_id", "status") VALUES (NEW."body", NEW."moderator_id", NEW."moderator_note", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason_id", NEW."status"); RETURN NULL;', hash='704a37c7d16a5909d5760f9ff9ac0b050087fcc7', operation='UPDATE', pgid='pgtrigger_update_update_68fde', table='moderation_report', when='AFTER')),
        ),
    ]
