# Generated by Django 6.0.1 on 2026-01-17 17:12

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='room.room'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='moderator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='body_reason_status_moderator_note_moderator_events', to='moderation.report'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='moderation__status_2a84ce_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'created_at'], name='moderation__user_id_1e46cf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['room', 'created_at'], name='moderation__room_id_a5943f_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'UNDER_REVIEW'))), fields=('user', 'room'), name='unique_active_report_per_user_room', violation_error_message='You already have an active report targeting this room.'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='report',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "moderation_reporthistory" ("body", "moderator_id", "moderator_note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "status") VALUES (NEW."body", NEW."moderator_id", NEW."moderator_note", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason", NEW."status"); RETURN NULL;', hash='72a864b71a366b163c7de390698b9618e4b96536', operation='INSERT', pgid='pgtrigger_insert_insert_62e14', table='moderation_report', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='report',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."moderator_id" IS DISTINCT FROM (NEW."moderator_id") OR OLD."moderator_note" IS DISTINCT FROM (NEW."moderator_note") OR OLD."reason" IS DISTINCT FROM (NEW."reason") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "moderation_reporthistory" ("body", "moderator_id", "moderator_note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "status") VALUES (NEW."body", NEW."moderator_id", NEW."moderator_note", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason", NEW."status"); RETURN NULL;', hash='e490ae0eccd3e82c8b875f69cca62984b886e722', operation='UPDATE', pgid='pgtrigger_update_update_68fde', table='moderation_report', when='AFTER')),
        ),
    ]
