# Generated by Django 5.1.4 on 2025-02-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.svg', upload_to='avatars'),
        ),
    ]
