# Generated by Django 5.1.4 on 2025-02-13 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_room_host_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.svg', upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg'])]),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('host', 'slug')},
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['host', 'slug'], name='core_room_host_id_c74c70_idx'),
        ),
    ]
