# Generated by Django 5.1.4 on 2025-02-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_slug_alter_room_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('host', 'name')},
        ),
    ]
