# Generated by Django 5.2.10 on 2026-01-19 13:42

import backend.account.files.paths
import backend.account.managers
import backend.core.files.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('bio', models.TextField(blank=True, default='', max_length=4096)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=backend.account.files.paths.avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg']), backend.core.files.validators.ImageValidator(), backend.core.files.validators.FileSizeValidator(10)])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': [models.OrderBy(django.db.models.functions.text.Lower('username'))],
            },
            managers=[
                ('objects', backend.account.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBanHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('banned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_banned_by_reason_expires_at_is_active_events', to='account.userban')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('username', models.SlugField(db_index=False, max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='username_email_is_active_is_staff_is_superuser_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='account_use_email_553b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='account_use_usernam_19aad5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='account_use_date_jo_403b71_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_userhistory" ("email", "is_active", "is_staff", "is_superuser", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (NEW."email", NEW."is_active", NEW."is_staff", NEW."is_superuser", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."username"); RETURN NULL;', hash='ad130f011ef5f09c368c9a2d95141e07c7fc8d67', operation='INSERT', pgid='pgtrigger_insert_insert_ae8bc', table='account_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."username" IS DISTINCT FROM (NEW."username"))', func='INSERT INTO "account_userhistory" ("email", "is_active", "is_staff", "is_superuser", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (NEW."email", NEW."is_active", NEW."is_staff", NEW."is_superuser", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."username"); RETURN NULL;', hash='b34eacaa29598f7c8fbc82380d5a713db82efda5', operation='UPDATE', pgid='pgtrigger_update_update_66d56', table='account_user', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['user', 'is_active'], name='account_use_user_id_c3b2bc_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userban',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "account_userbanhistory" ("banned_by_id", "expires_at", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "user_id") VALUES (NEW."banned_by_id", NEW."expires_at", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason", NEW."user_id"); RETURN NULL;', hash='1564629af00205a4c7750570fd1d0e3ad33fe04a', operation='INSERT', pgid='pgtrigger_insert_insert_ed528', table='account_userban', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userban',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."banned_by_id" IS DISTINCT FROM (NEW."banned_by_id") OR OLD."expires_at" IS DISTINCT FROM (NEW."expires_at") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."reason" IS DISTINCT FROM (NEW."reason") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))', func='INSERT INTO "account_userbanhistory" ("banned_by_id", "expires_at", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "user_id") VALUES (NEW."banned_by_id", NEW."expires_at", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason", NEW."user_id"); RETURN NULL;', hash='118fd4ba3400cfa7e4b6138a6b5d3386e63abf72', operation='UPDATE', pgid='pgtrigger_update_update_0508a', table='account_userban', when='AFTER')),
        ),
    ]
