# Generated by Django 5.2.10 on 2026-01-19 13:42

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_initial'),
        ('invite', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='room.room'),
        ),
        migrations.AddField(
            model_name='invitehistory',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='invitehistory',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_role_events', to='invite.invite'),
        ),
        migrations.AddField(
            model_name='invitehistory',
            name='role',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='access.role'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['room', 'invitee'], name='invite_invi_room_id_b83e41_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['expires_at'], name='invite_invi_expires_39f247_idx'),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('room', 'invitee'), name='unique_invite_per_user_room', violation_error_message='This user has already been invited to this room.'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invite',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "invite_invitehistory" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "status") VALUES (_pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_id", NEW."status"); RETURN NULL;', hash='0818fa9740f24ff58e478023940999e3bc662509', operation='INSERT', pgid='pgtrigger_insert_insert_c9730', table='invite_invite', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invite',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."role_id" IS DISTINCT FROM (NEW."role_id") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "invite_invitehistory" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "status") VALUES (_pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role_id", NEW."status"); RETURN NULL;', hash='1e27c399d223d89c4dd34aef012b7d0b79a473b7', operation='UPDATE', pgid='pgtrigger_update_update_acea6', table='invite_invite', when='AFTER')),
        ),
    ]
