# Generated by Django 6.0.4 on 2026-04-08 19:05

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('room.delete', 'Delete room'), ('room.update', 'Update room settings'), ('room.manage_visibility', 'Manage room visibility settings'), ('room.manage_participants', 'Invite or remove participants'), ('room.manage_roles', 'Manage room roles and permissions'), ('room.delete_message', 'Delete message'), ('room.upload_file', 'Allow file uploads')], editable=False, max_length=64, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
