# Generated by Django 6.0 on 2025-12-31 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.room'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='access_perm_code_7d6a09_idx'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='access.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.room'),
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.role'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='unique_role_name_per_room'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'joined_at'], name='access_part_room_id_880552_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'user'], name='access_part_room_id_341e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'role'], name='access_part_room_id_9a1d86_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user', 'joined_at'], name='access_part_user_id_028956_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user'], name='access_part_user_id_2c4840_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_participant'),
        ),
    ]
