# Generated by Django 6.0 on 2025-12-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_initial'),
        ('access', '0004_add_room_relations'),
    ]

    operations = [
    ]
