# Generated by Django 5.2.10 on 2026-01-19 13:42

import django.db.models.deletion
import django.db.models.functions.text
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_rooms', to='access.role')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', through='access.Participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('visibility', models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=16)),
                ('default_role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='access.role')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_description_visibility_default_role_events', to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': [models.OrderBy(django.db.models.functions.text.Lower('name'))],
                'indexes': [models.Index(fields=['name'], name='room_topic_name_40cbd6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '^[A-Za-z]+$')), name='letters_only_in_topic_name', violation_error_message='Topic name must consist of letters only.')],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='topics',
            field=models.ManyToManyField(related_name='rooms', to='room.topic'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['updated_at'], name='room_room_updated_0192af_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('host', 'name'), name='unique_room_per_host', violation_error_message='You already have a room with this name.'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='room',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "room_roomhistory" ("default_role_id", "description", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "visibility") VALUES (NEW."default_role_id", NEW."description", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."visibility"); RETURN NULL;', hash='ca40c8f418a8bc3c52c3ac6265a26a2f09de9697', operation='INSERT', pgid='pgtrigger_insert_insert_16559', table='room_room', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='room',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."default_role_id" IS DISTINCT FROM (NEW."default_role_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."visibility" IS DISTINCT FROM (NEW."visibility"))', func='INSERT INTO "room_roomhistory" ("default_role_id", "description", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "visibility") VALUES (NEW."default_role_id", NEW."description", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."visibility"); RETURN NULL;', hash='d2009f52d91f22e139a9ade3bb019a1290a2508a', operation='UPDATE', pgid='pgtrigger_update_update_9df71', table='room_room', when='AFTER')),
        ),
    ]
