# Generated by Django 6.0 on 2025-12-25 14:17

import backend.core.managers
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('bio', models.TextField(blank=True, default='', max_length=4096)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('username')],
            },
            managers=[
                ('objects', backend.core.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('room.delete', 'Delete room'), ('room.update', 'Update room'), ('room.manage_visibility', 'Manage room visibility'), ('room.invite', 'Invite users'), ('room.kick', 'Remove users'), ('room.role_manage', 'Manage roles'), ('room.delete_message', 'Delete message'), ('room.upload_file', 'Allow file uploads')], editable=False, max_length=64, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='core_permis_code_4d467b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('priority', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_rooms', to='core.role')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', through='core.Participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.room'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2048)),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('HARASSMENT', 'Harassment'), ('INAPPROPRIATE_CONTENT', 'Inappropriate Content'), ('HATE_SPEECH', 'Hate Speech'), ('OTHER', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=32)),
                ('moderator_note', models.TextField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.room'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2048)),
                ('is_edited', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
                'indexes': [models.Index(fields=['name'], name='core_topic_name_ed0efc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '^[A-Za-z]+$')), name='letters_only_in_topic_name', violation_error_message='Topic name must consist of letters only.')],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='topics',
            field=models.ManyToManyField(related_name='rooms', to='core.topic'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='core_user_usernam_e8adca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='core_user_date_jo_a935f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='unique_role_name_per_room'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='core_report_status_9a134a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'created_at'], name='core_report_user_id_1d49fb_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['room', 'created_at'], name='core_report_room_id_902a2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'UNDER_REVIEW'])), fields=('user', 'room'), name='unique_active_report_per_user_room', violation_error_message='You already have an active report targeting this room.'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'joined_at'], name='core_partic_room_id_2e206a_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'user'], name='core_partic_room_id_ce3213_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'role'], name='core_partic_room_id_fa9c67_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user', 'joined_at'], name='core_partic_user_id_4b6863_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user'], name='core_partic_user_id_a1648c_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_participant'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'user', 'created_at'], name='core_messag_room_id_eea8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='core_messag_room_id_4c5105_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='core_messag_room_id_0caefd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'created_at'], name='core_messag_user_id_86f77e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user'], name='core_messag_user_id_008e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['room', 'invitee'], name='core_invite_room_id_da8bba_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['expires_at'], name='core_invite_expires_d1b304_idx'),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('room', 'invitee'), name='unique_invite_per_user_room', violation_error_message='This user has already been invited to this room.'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['updated_at'], name='core_room_updated_18da45_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('host', 'slug'), name='unique_room_per_host', violation_error_message='You already have a room with this name.'),
        ),
    ]
