# Generated by Django 6.0.1 on 2026-01-13 20:29

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pghistory.events',),
            managers=[
                ('no_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
