# Generated by Django 5.2.8 on 2025-11-11 21:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2048, validators=[django.core.validators.MaxLengthValidator(2048)])),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('HARASSMENT', 'Harassment'), ('INAPPROPRIATE_CONTENT', 'Inappropriate Content'), ('HATE_SPEECH', 'Hate Speech'), ('OTHER', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=32)),
                ('moderator_note', models.TextField(blank=True, default='', max_length=512, validators=[django.core.validators.MaxLengthValidator(512)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['status', 'created'], name='core_report_status_ba5938_idx'), models.Index(fields=['user', 'created'], name='core_report_user_id_0aeca2_idx'), models.Index(fields=['room', 'created'], name='core_report_room_id_acb3ae_idx')],
            },
        ),
    ]
