# Generated by Django 5.2 on 2025-04-18 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.svg', upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['topic'], name='core_room_topic_i_552a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['updated'], name='core_room_updated_c625fe_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='core_user_usernam_e8adca_idx'),
        ),
    ]
