# Generated by Django 5.2.8 on 2025-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'UNDER_REVIEW'])), fields=('user', 'room'), name='unique_active_report_per_user_room', violation_error_message='You already have an active report targeting this room.'),
        ),
    ]
