# Generated by Django 6.0 on 2025-12-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_unique_active_report_per_user_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=2),
        ),
    ]
