# Generated by Django 5.2 on 2025-05-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_edited'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='room',
            name='unique_room_per_host',
            constraint=models.UniqueConstraint(fields=('host', 'name'), name='unique_room_per_host', violation_error_message='You already have a room with this name.'),
        ),
    ]
