# Generated by Django 5.2.7 on 2025-10-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_message_body_alter_room_description_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='room',
            name='core_room_topic_i_552a3d_idx',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.AddField(
            model_name='room',
            name='topics',
            field=models.ManyToManyField(related_name='rooms', to='core.topic'),
        ),
    ]
