# Generated by Django 5.2 on 2025-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_room_unique_room_per_host'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^[A-Za-z]+$'), _negated=True), name='no_spaces_in_topic', violation_error_message='Topic name must consist of letters only.'),
        ),
    ]
