# Generated by Django 5.2 on 2025-05-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_topic_no_spaces_in_topic'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='topic',
            name='no_spaces_in_topic',
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^[A-Za-z]+$')), name='no_spaces_in_topic', violation_error_message='Topic name must consist of letters only.'),
        ),
    ]
