name: Frontend Lint

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.0.1
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      - name: Run ESLint
        working-directory: ./frontend
        run: pnpm exec eslint .
